hugoblox:
  schema: "2.0"
  identity:
    name: ""
    type: person
    tagline: ""
    description: ""
  theme:
    mode: system
    pack: minimal
    colors:
      primary: purple
      secondary: ""
      neutral: ""
  typography:
    font: minimal
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
# 1. 页脚设置
  footer:
    style: minimal
    language_switcher: false
    show_powered_by: false  # 尝试关掉 Powered by
    text: ""                # 【关键】强制把默认的推广文字覆盖为空！

  # 2. 版权与协议设置
  copyright:
    notice: '© 2025-{year} Chengyuan Huang. This work is licensed under CC BY NC ND 4.0'
    license:
      enable: true
      allow_commercial: false
      allow_derivatives: false
      share_alike: false
